INSERT INTO (CODIGO, NOME, MARCA, TRIBUTACAO, PRECO) VALUES (1, 'GOL BOLINHA', 'VOLKSWAGEN', 'False', 500.0)

INSERT INTO (CODIGO, NOME, MARCA, TRIBUTACAO, PRECO) VALUES (2, 'True', 'CALOI', 'False', 100.0)

INSERT INTO (CODIGO, NOME, MARCA, TRIBUTACAO, PRECO) VALUES (3, 'True', 'S.H.I.E.L.D.', 'True', 40000.65)

INSERT INTO (CODIGO, NOME, MARCA, TRIBUTACAO, PRECO) VALUES (4, 'True', 'False', 'False', 2000.0)

INSERT INTO (CODIGO, NOME, MARCA, TRIBUTACAO, PRECO) VALUES (5, 'True', 'True', 'True', 50.0)

INSERT INTO (NOME, CPF, CNPJ, ENDEREÇO, BAIRRO, FORNECEDOR) VALUES ('SEIYA DE PEGASO', '25546769092', '', 'Rua beabá, 12', 'Centro', 'True')

INSERT INTO (NOME, CPF, CNPJ, ENDEREÇO, BAIRRO, FORNECEDOR) VALUES ('SHIRYU DE DRAGAO', '', '28902657000163', 'Ave Jota, 54', 'Sul', 'False')

INSERT INTO (NOME, CPF, CNPJ, ENDEREÇO, BAIRRO, FORNECEDOR) VALUES ('IKKI DE FENIX', '69897427040', '', 'Rua dois, n 13', 'Norte', 'False')

INSERT INTO (NOME, CPF, CNPJ, ENDEREÇO, BAIRRO, FORNECEDOR) VALUES ('HYOGA DE CISNE', '', '34204661000150', 'Praça dos anjos, 13', 'Centro', 'True')

